defaults:
  - model: BERT_NO_POOL
  - data: SST2

log:
  dir: resource/log/

model_checkpoint:
  dir: resource/model_checkpoint/

representation:
  fold: 0
  dir: resource/representation/${model.name}_${data.name}/
  write_interval: batch
  PAD: ${model.PAD}


tasks: ["fit", "test", "predict"]

trainer:
  max_epochs: 16
  gpus: 1
  patience: 7
  min_delta: 0.05
  precision: 16
  fast_dev_run: False
  progress_bar_refresh_rate: 1
